#!/usr/bin/env ruby
#
# github-sync - checks out all your projects on GitHub under your local directory
#
# How to set up:
#     $ GITHUB_DIR=$HOME/github.com; export GITHUB_DIR
#     # or you will have $HOME/src/github.com by default
#
# How to use:
#     $ github-sync
#
# Copyright (c) 2009-2019 Akinori MUSHA
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

require 'yaml'
require 'faraday'
require 'faraday_middleware'
require 'shellwords'
require 'optparse'

def setup
  $base_dir = ENV['GITHUB_DIR'] || File.expand_path('~/src/github.com')
  $new_only = false
  $exclude = (ENV['GITHUB_SYNC_EXCLUDE'] || '').split
end

def get_token
  hub_config = File.expand_path('~/.config/hub')
  raise "hub is not configured" unless File.file?(hub_config)

  YAML.load_file(hub_config)['github.com'].each { |hash|
    if token = hash["oauth_token"]
      return token
    end
  }
  raise "token not found"
end

def main(argv)
  setup
  OptionParser.new { |opts|
    opts.on('-N') { |bool| $new_only = bool }
    opts.on('-x PATTERN') { |name| $exclude << name }
    opts.parse!(argv)
  }
  checkout_all
end

def ua
  $ua ||= Faraday.new('https://api.github.com/', headers: { 'Authorization' => "token #{get_token}" }) { |faraday|
    faraday.response :json, content_type: /\bjson\z/
    faraday.adapter  Faraday.default_adapter
  }
end

def github_get_all(path, result = [])
  res = ua.get(path)

  result.concat(res.body)

  if links = res.headers['Link']
    links.scan(/(?:\A|\G, *)<([^>]+)>; *rel="([^"]+)"/) { |link, rel|
      return github_get_all(link, result) if rel == 'next'
    }
  end

  result
end

def get_repos
  github_get_all('/user/repos')
end

def checkout_all
  repos = get_repos.sort_by { |repo| repo['full_name'] }

  Dir.mkdir($base_dir) if !File.directory?($base_dir)
  Dir.chdir($base_dir)

  repos.each { |repo|
    dir = repo['full_name']
    name = repo['name']
    next if $exclude.any? { |pattern|
      if pattern.include?('/')
        File.fnmatch(pattern, dir, File::FNM_PATHNAME)
      else
        File.fnmatch(pattern, name, File::FNM_PATHNAME)
      end
    }

    if File.directory?(dir)
      next if $new_only
      puts '==> Updating %s' % repo['full_name']
      Dir.chdir(dir) {
        system 'git remote update'
        local = `git symbolic-ref HEAD 2>/dev/null`.strip
        $?.success? && !local.empty? or break
        remote = `git for-each-ref --format='%(upstream:short)' #{local.shellescape} 2>/dev/null`.strip
        $?.success? && !remote.empty? or break
        system 'git', 'rebase', remote
        system 'git submodule update --init --recursive'
      }
    else
      puts '==> Cloning into %s' % repo['full_name']
      system 'git', 'clone', '--recursive', repo['ssh_url'], dir
    end

    if repo['fork'] && !Dir.chdir(dir) {
        `git remote 2>/dev/null`
      }.split(' ').include?('upstream')
    then
      detail = ua.get('https://api.github.com/repos/%s' % dir).body
      upstream_url = detail['parent']['clone_url']
      puts 'Registering upstream repository: %s' % upstream_url
      Dir.chdir(dir) {
        system 'git', 'remote', 'add', 'upstream', upstream_url
      }
    end

    puts ''
  }
end

main(ARGV)
